version: "3.5"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - postgres_test
      - redis
    env_file:
      - .env
    networks:
      - app-network

  postgres:
    container_name: postgres16
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: carparking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  postgres_test:
    container_name: postgres16_test
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: roottest
      POSTGRES_PASSWORD: secrettest
      POSTGRES_DB: carparkingtest
    ports:
      - "5433:5433"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    container_name: redis6
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis_data:/data

  test:
    build: .
    command: npm test
    depends_on:
      - postgres_test
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - .:/app
    working_dir: /app

networks:
  app-network:

volumes:
  postgres_data:
  postgres_test_data:
  redis_data:
